In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [14]:
#                                         Numpy 

import numpy as np 

# creating a numpy 1d array 

arr1 = np.array([1,2,3,4,5]) ; 
print(type(arr1)) ; 



arr1

arr1.shape





<class 'numpy.ndarray'>


(5,)

In [6]:
#        creating a 2d or more dimensional numpy array 

import numpy as np 
arr = np.array([1,2,3,4,5]) ; 
# reshaping is reshape my arr into 1 row and 5 column 
arr.reshape(1,5) ;     
arr




array([1, 2, 3, 4, 5])

In [21]:
#  creating multidimensional array without using reshape 
import numpy as np 
arr2 = np.array([[1,2,3,4], [5,6,7,8]]) ; 
print(arr2) ; 
print(arr2.shape) ; 

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [31]:
import numpy as np 

# made an array and reshaped it into 5 rows and 1 column 
arr = np.arange(0,10,2).reshape(5,1) ; 
arr

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [34]:
import numpy as np 
ones = np.ones((3,4)) ; 
ones 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [36]:
#     identity matrix 

i = np.eye(3) ; 
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [46]:
#  Numpy vectorized operation 
import numpy as np 
arr1 = np.array([[1,2,3,4,5],[1,2,3,4,5]]) ; 
arr2  = np.array([[1,2,3,4,5],[1,2,3,4,5]]) ; 

print() ; 
print("Addition" , arr1+arr2) ; 
print() ; 
print("substraction" , arr1-arr2) ; 
# Element wise multiplication
print() ; 
print("Element wise multiplication " , arr1 * arr2) ; 



Addition [[ 2  4  6  8 10]
 [ 2  4  6  8 10]]

substraction [[0 0 0 0 0]
 [0 0 0 0 0]]

Element wise multiplication  [[ 1  4  9 16 25]
 [ 1  4  9 16 25]]
