In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
import numpy as np 

# Datatypes and Attributes 

In [3]:
# Numpy main datatype is ndarray 

# 1 dimension 

a = np.array([1,2,3])

a

array([1, 2, 3])

In [4]:
# 2 dimension
a1 = np.array([[1,2,3] , [4,5,6]])
a1


array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
# 3 dimension 
a3 = np.array([[[1,2,3] , [4,5,6] , [7,8,9.3]] , [[10,11,12] , [13,14,15] , [16,17,18]]])
a3

array([[[ 1. ,  2. ,  3. ],
        [ 4. ,  5. ,  6. ],
        [ 7. ,  8. ,  9.3]],

       [[10. , 11. , 12. ],
        [13. , 14. , 15. ],
        [16. , 17. , 18. ]]])

In [6]:
a.shape , a1.shape , a3.shape

((3,), (2, 3), (2, 3, 3))

In [7]:
# dimensions of a , a1 , and a3
a.ndim , a1.ndim , a3.ndim 

(1, 2, 3)

In [8]:
# datatypes of a , a1 , and a3

a.dtype , a1.dtype , a3.dtype 

(dtype('int64'), dtype('int64'), dtype('float64'))

In [9]:
a.size , a1.size , a3.size

(3, 6, 18)

In [10]:
type(a) , type(a1) , type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

# Creating Arrays 

In [11]:
ones = np.ones(5)
ones 

one = np.ones((2,5))
one

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
# start from 0 stop at 10 with a jump of 2 
range_array = np.arange(0,10,2)
range_array 

array([0, 2, 4, 6, 8])

In [13]:
# this is just going to have a number between 0 to 10 but if you want an array 
# you need to specify the size like the example below
random = np.random.randint(0,10)
random 

# creating a random array of size 3 * 5 

random_array = np.random.randint(0,10,size=(3,5))
random_array 


array([[7, 9, 9, 8, 9],
       [9, 3, 2, 3, 7],
       [2, 2, 7, 2, 4]])

In [14]:
# This gives a random array of size specified i.e 3x5 having numbers between 0 to 1 
# Note that it is not randint but random 
random_array2 = np.random.random((3,5))
random_array2

array([[0.80871978, 0.2123922 , 0.02166433, 0.72067054, 0.28105789],
       [0.60706427, 0.88161128, 0.51012393, 0.09417464, 0.57529452],
       [0.52900432, 0.10729944, 0.77745014, 0.69521388, 0.93680029]])

# Random Seed 


In [15]:
# It is Used to store your random number in case you want to share your notebook so 
# you dont get different random numbers everytime you run the cell 

# The number inside it can be anything its just that whenver it sees 4 it returns that 
# particular random array 
np.random.seed(4)
random_array5 = np.random.randint(10, size=(3,5))
random_array5

array([[7, 5, 1, 8, 7],
       [8, 2, 9, 7, 7],
       [7, 9, 8, 4, 2]])

# Viewing Arrays and Matrices 

In [16]:
# finding unique element from a numpy array 

np.unique(random_array5)

array([1, 2, 4, 5, 7, 8, 9])

In [17]:
# A 4 dimensional array 
arr = np.random.randint(10 , size= (2,3,4,5))
arr 

array([[[[6, 4, 3, 0, 7],
         [5, 5, 9, 6, 6],
         [8, 2, 5, 8, 1],
         [2, 7, 0, 8, 3]],

        [[1, 0, 3, 2, 3],
         [2, 9, 2, 1, 0],
         [1, 9, 9, 0, 7],
         [2, 6, 3, 7, 8]],

        [[2, 6, 7, 7, 9],
         [2, 7, 5, 3, 0],
         [5, 4, 3, 8, 9],
         [5, 8, 6, 7, 0]]],


       [[[4, 6, 8, 4, 8],
         [1, 9, 5, 4, 2],
         [3, 4, 7, 6, 6],
         [8, 0, 3, 5, 6]],

        [[1, 1, 6, 0, 8],
         [7, 5, 7, 6, 8],
         [4, 4, 0, 7, 2],
         [1, 8, 8, 1, 3]],

        [[1, 3, 6, 7, 4],
         [0, 7, 3, 7, 9],
         [6, 6, 9, 3, 2],
         [7, 6, 7, 9, 4]]]])

In [18]:
# Get the first three numbers from the inner most arrays 
arr[1,0,0,:3]

array([4, 6, 8])

In [19]:
# Get the first 2 numbers from each row
arr[:,:,:,:2]

array([[[[6, 4],
         [5, 5],
         [8, 2],
         [2, 7]],

        [[1, 0],
         [2, 9],
         [1, 9],
         [2, 6]],

        [[2, 6],
         [2, 7],
         [5, 4],
         [5, 8]]],


       [[[4, 6],
         [1, 9],
         [3, 4],
         [8, 0]],

        [[1, 1],
         [7, 5],
         [4, 4],
         [1, 8]],

        [[1, 3],
         [0, 7],
         [6, 6],
         [7, 6]]]])

# Manipulating Arrays 

## Arithmetic 

In [20]:
a1  =[1,2,3]
ones = np.ones(3)

a1 + ones 

array([2., 3., 4.])

In [21]:
a1 * ones 

array([1., 2., 3.])

In [22]:
a2 = np.ones((2,3))
a2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
a1*a2

array([[1., 2., 3.],
       [1., 2., 3.]])

In [24]:
a1 / ones 

array([1., 2., 3.])

In [25]:
a2 / a1

array([[1.        , 0.5       , 0.33333333],
       [1.        , 0.5       , 0.33333333]])

In [26]:
a2 // a1

array([[1., 0., 0.],
       [1., 0., 0.]])

In [27]:
# square of each number inside the array 
a2 ** 2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [28]:
np.exp(a2)

array([[2.71828183, 2.71828183, 2.71828183],
       [2.71828183, 2.71828183, 2.71828183]])

In [29]:
np.log(a2)

array([[0., 0., 0.],
       [0., 0., 0.]])