In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
import numpy as np 
import pandas as pd 

# Datatypes and Attributes 

In [3]:
# Numpy main datatype is ndarray 

# 1 dimension 

a = np.array([1,2,3])

a

array([1, 2, 3])

In [4]:
# 2 dimension
a1 = np.array([[1,2,3] , [4,5,6]])
a1


array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
# 3 dimension 
a3 = np.array([[[1,2,3] , [4,5,6] , [7,8,9.3]] , [[10,11,12] , [13,14,15] , [16,17,18]]])
a3

array([[[ 1. ,  2. ,  3. ],
        [ 4. ,  5. ,  6. ],
        [ 7. ,  8. ,  9.3]],

       [[10. , 11. , 12. ],
        [13. , 14. , 15. ],
        [16. , 17. , 18. ]]])

In [6]:
a.shape , a1.shape , a3.shape

((3,), (2, 3), (2, 3, 3))

In [7]:
# dimensions of a , a1 , and a3
a.ndim , a1.ndim , a3.ndim 

(1, 2, 3)

In [8]:
# datatypes of a , a1 , and a3

a.dtype , a1.dtype , a3.dtype 

(dtype('int64'), dtype('int64'), dtype('float64'))

In [9]:
a.size , a1.size , a3.size

(3, 6, 18)

In [10]:
type(a) , type(a1) , type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

# Creating Arrays 

In [11]:
ones = np.ones(5)
ones 

one = np.ones((2,5))
one

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
# start from 0 stop at 10 with a jump of 2 
range_array = np.arange(0,10,2)
range_array 

array([0, 2, 4, 6, 8])

In [13]:
# this is just going to have a number between 0 to 10 but if you want an array 
# you need to specify the size like the example below
random = np.random.randint(0,10)
random 

# creating a random array of size 3 * 5 

random_array = np.random.randint(0,10,size=(3,5))
random_array 


array([[4, 5, 4, 6, 6],
       [5, 1, 3, 8, 4],
       [6, 1, 6, 0, 7]])

In [14]:
# This gives a random array of size specified i.e 3x5 having numbers between 0 to 1 
# Note that it is not randint but random 
random_array2 = np.random.random((3,5))
random_array2

array([[0.79323994, 0.06559728, 0.80469434, 0.83682047, 0.31713948],
       [0.45566258, 0.64792102, 0.5862224 , 0.0152157 , 0.20421186],
       [0.27774961, 0.29669701, 0.97453469, 0.85118815, 0.43271261]])

# Random Seed 


In [15]:
# It is Used to store your random number in case you want to share your notebook so 
# you dont get different random numbers everytime you run the cell 

# The number inside it can be anything its just that whenver it sees 4 it returns that 
# particular random array 
np.random.seed(4)
random_array5 = np.random.randint(10, size=(3,5))
random_array5

array([[7, 5, 1, 8, 7],
       [8, 2, 9, 7, 7],
       [7, 9, 8, 4, 2]])

# Viewing Arrays and Matrices 

In [16]:
# finding unique element from a numpy array 

np.unique(random_array5)

array([1, 2, 4, 5, 7, 8, 9])

In [17]:
# A 4 dimensional array 
arr = np.random.randint(10 , size= (2,3,4,5))
arr 

array([[[[6, 4, 3, 0, 7],
         [5, 5, 9, 6, 6],
         [8, 2, 5, 8, 1],
         [2, 7, 0, 8, 3]],

        [[1, 0, 3, 2, 3],
         [2, 9, 2, 1, 0],
         [1, 9, 9, 0, 7],
         [2, 6, 3, 7, 8]],

        [[2, 6, 7, 7, 9],
         [2, 7, 5, 3, 0],
         [5, 4, 3, 8, 9],
         [5, 8, 6, 7, 0]]],


       [[[4, 6, 8, 4, 8],
         [1, 9, 5, 4, 2],
         [3, 4, 7, 6, 6],
         [8, 0, 3, 5, 6]],

        [[1, 1, 6, 0, 8],
         [7, 5, 7, 6, 8],
         [4, 4, 0, 7, 2],
         [1, 8, 8, 1, 3]],

        [[1, 3, 6, 7, 4],
         [0, 7, 3, 7, 9],
         [6, 6, 9, 3, 2],
         [7, 6, 7, 9, 4]]]])

In [18]:
# Get the first three numbers from the inner most arrays 
arr[1,0,0,:3]

array([4, 6, 8])

In [19]:
# Get the first 2 numbers from each row
arr[:,:,:,:2]

array([[[[6, 4],
         [5, 5],
         [8, 2],
         [2, 7]],

        [[1, 0],
         [2, 9],
         [1, 9],
         [2, 6]],

        [[2, 6],
         [2, 7],
         [5, 4],
         [5, 8]]],


       [[[4, 6],
         [1, 9],
         [3, 4],
         [8, 0]],

        [[1, 1],
         [7, 5],
         [4, 4],
         [1, 8]],

        [[1, 3],
         [0, 7],
         [6, 6],
         [7, 6]]]])

# Manipulating Arrays 

## Arithmetic 

In [20]:
a1  =[1,2,3]
ones = np.ones(3)

a1 + ones 

array([2., 3., 4.])

In [21]:
a1 * ones 

array([1., 2., 3.])

In [22]:
a2 = np.ones((2,3))
a2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
a1*a2

array([[1., 2., 3.],
       [1., 2., 3.]])

In [24]:
a1 / ones 

array([1., 2., 3.])

In [25]:
a2 / a1

array([[1.        , 0.5       , 0.33333333],
       [1.        , 0.5       , 0.33333333]])

In [26]:
a2 // a1

array([[1., 0., 0.],
       [1., 0., 0.]])

In [27]:
# square of each number inside the array 
a2 ** 2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [28]:
np.exp(a2)

array([[2.71828183, 2.71828183, 2.71828183],
       [2.71828183, 2.71828183, 2.71828183]])

In [29]:
np.log(a2)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [30]:
massive_array = np.random.random(1000000)
massive_array[:100]

array([0.41903403, 0.90242186, 0.97961626, 0.62356884, 0.08318412,
       0.73299872, 0.6786854 , 0.82602287, 0.34745134, 0.05888009,
       0.61182182, 0.12401462, 0.75952953, 0.79442332, 0.40862679,
       0.94379751, 0.17377979, 0.94258585, 0.46548967, 0.76299364,
       0.7528202 , 0.98120992, 0.97327799, 0.04009112, 0.01597128,
       0.54329032, 0.03387762, 0.65748464, 0.5349026 , 0.6665584 ,
       0.4413407 , 0.27247146, 0.94966894, 0.72826944, 0.00632394,
       0.09932776, 0.63169225, 0.28803683, 0.40762168, 0.78153112,
       0.35414554, 0.9258086 , 0.72045212, 0.55192644, 0.18096484,
       0.40959139, 0.76288179, 0.99079682, 0.07365237, 0.13475261,
       0.74004473, 0.83378137, 0.08877286, 0.82941795, 0.78673231,
       0.68822127, 0.33992642, 0.44454066, 0.36633614, 0.84046606,
       0.32832214, 0.32257498, 0.93529086, 0.91998735, 0.96867413,
       0.80754895, 0.08691562, 0.09091055, 0.55708208, 0.85618377,
       0.88419786, 0.63684867, 0.95580459, 0.1518856 , 0.22158

In [31]:
# python's list method for summation 
%timeit sum(massive_array) 
# numpy method for summatiion 
%timeit np.sum(massive_array)

# timeit tells the time for the execution the result shows that numpy sum method is 
# is way faster

109 ms ± 2.45 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
618 µs ± 48.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [32]:
np.min(a2)
np.max(a2)
np.std(a2)
np.mean(a2)
np.var(a2)

0.0

In [33]:
# The array contains 2 blocks. 
# Each block contains 3 matrices.
# Each matrix has 4 rows and 5 columns.


mas = np.random.randint(10 , size=(2,3,4,5))
mas 


array([[[[0, 4, 8, 0, 1],
         [6, 4, 5, 6, 8],
         [9, 7, 7, 6, 8],
         [7, 9, 9, 9, 9]],

        [[4, 2, 5, 3, 0],
         [5, 3, 4, 5, 8],
         [5, 7, 3, 9, 9],
         [4, 2, 3, 7, 4]],

        [[1, 5, 0, 9, 1],
         [5, 8, 2, 1, 0],
         [4, 2, 7, 3, 5],
         [1, 5, 4, 3, 5]]],


       [[[6, 1, 2, 1, 6],
         [4, 6, 8, 1, 1],
         [1, 1, 2, 4, 8],
         [3, 4, 1, 7, 8]],

        [[8, 8, 2, 4, 5],
         [7, 9, 4, 5, 7],
         [2, 9, 1, 5, 5],
         [1, 7, 4, 0, 7]],

        [[4, 7, 9, 2, 7],
         [9, 1, 3, 1, 7],
         [7, 3, 2, 6, 6],
         [1, 4, 6, 3, 1]]]])

# Reshaping and transpose 

In [34]:
a2 = np.random.random((2,3))
a2

array([[0.74714653, 0.85236057, 0.05090183],
       [0.50271457, 0.2668226 , 0.61411989]])

In [35]:
a3 = np.random.random((2,3,3))
a3

array([[[0.62198438, 0.59319787, 0.58450813],
        [0.42626905, 0.06761105, 0.28487813],
        [0.62133758, 0.4834754 , 0.89865986]],

       [[0.90394719, 0.27831016, 0.04150753],
        [0.34489867, 0.74584038, 0.28967697],
        [0.61090159, 0.37454401, 0.94704838]]])

### Here a2 * a3 is not possible we would need to reshape it 


we have reshaped a2 into 2,3,1 as rule of broadcasting says either the shape
is same or one of them is one. 


In [36]:
a2_reshape = a2.reshape(2,3,1)
# now a2 * a3 is possible 
a2_reshape* a3

array([[[0.46471347, 0.44320573, 0.43671323],
        [0.36333493, 0.05762899, 0.24281888],
        [0.03162722, 0.02460978, 0.04574343]],

       [[0.45442743, 0.13991057, 0.02086644],
        [0.09202676, 0.19900707, 0.07729236],
        [0.37516682, 0.23001492, 0.58160124]]])

# Transpose 

In [37]:
a2


array([[0.74714653, 0.85236057, 0.05090183],
       [0.50271457, 0.2668226 , 0.61411989]])

In [38]:
a2.T

array([[0.74714653, 0.50271457],
       [0.85236057, 0.2668226 ],
       [0.05090183, 0.61411989]])

In [39]:
tri = np.random.random(size=(2,3,4))
tri.T




array([[[0.05716923, 0.78971793],
        [0.4895375 , 0.72524745],
        [0.53513801, 0.31905649]],

       [[0.63826317, 0.24202759],
        [0.75342075, 0.55022295],
        [0.59642519, 0.09322237]],

       [[0.5718038 , 0.63087597],
        [0.75470732, 0.75715432],
        [0.96619398, 0.07695795]],

       [[0.6994457 , 0.26848217],
        [0.26657531, 0.19759386],
        [0.64797938, 0.11030597]]])

# Dot Product 

In [40]:
np.random.seed(0)
mat1 = np.random.randint(10 , size=(2,3))
mat1

array([[5, 0, 3],
       [3, 7, 9]])

In [41]:
np.random.seed(1)

mat2 = np.random.randint(10 , size=(3,2))
mat2




array([[5, 8],
       [9, 5],
       [0, 0]])

In [42]:
np.dot(mat1 , mat2)

array([[25, 40],
       [78, 59]])

# Dot Product example (sales_data)



In [43]:
sales_amounts = np.random.randint(20 , size=(5,3))
sales_amounts

array([[ 1, 12,  7],
       [13,  6, 18],
       [ 5, 18, 11],
       [10, 14, 18],
       [ 4,  9, 17]])

In [44]:
import pandas as pd 
weekly_sales = pd.DataFrame(sales_amounts , index=["Mon","Tue","Wed","Thu","Fri"],
                           columns = ["Almond" , "Peanut" , "Cashew"])

weekly_sales



Almond  Peanut  Cashew
Mon       1      12       7
Tue      13       6      18
Wed       5      18      11
Thu      10      14      18
Fri       4       9      17

# Creating prices section 

In [45]:

prices = np.array([10,12,15])


# Here notice that shape of prices is 3, but to put in dataFrame you want 1x3 so 
# reshape it 

butter_prices = pd.DataFrame(prices.reshape(1,3) , index=["Price"] , columns = ["Almond" , 
                                                                  "Peanut",
                                                                  "Cashew"])
butter_prices



Almond  Peanut  Cashew
Price      10      12      15

In [46]:
butter_prices

Almond  Peanut  Cashew
Price      10      12      15

In [47]:
# daily_sales = np.dot(weekly_sales,butter_prices.T)
# Total_price = pd.DataFrame(daily_sales ,index=["Mon","Tue","Wed","Thu","Fri"],
                          # columns = ["Total_Sale"])

# the above dot product gives ndarray and the below gives dataframe 
daily_sales = weekly_sales.dot(butter_prices.T)


daily_sales 




Price
Mon    259
Tue    472
Wed    431
Thu    538
Fri    403

In [48]:
weekly_sales["Total"] = daily_sales

In [49]:
weekly_sales

Almond  Peanut  Cashew  Total
Mon       1      12       7    259
Tue      13       6      18    472
Wed       5      18      11    431
Thu      10      14      18    538
Fri       4       9      17    403

# Comparison Operator 

In [50]:
np.random.seed(0)
a1 = np.random.randint(10 , size=(3))
a1

array([5, 0, 3])

In [51]:
np.random.seed(1)
a2 = np.random.randint(10 , size=(3))
a2


array([5, 8, 9])

In [52]:
a1 == a2


array([ True, False, False])

# Sorting Arrays 

In [53]:
random_array = np.random.randint(10,size=(3,5))
random_array

array([[5, 0, 0, 1, 7],
       [6, 9, 2, 4, 5],
       [2, 4, 2, 4, 7]])

In [54]:
np.sort(random_array)

array([[0, 0, 1, 5, 7],
       [2, 4, 5, 6, 9],
       [2, 2, 4, 4, 7]])

In [55]:
# This sorts the indices for you 
np.argsort(random_array)

array([[1, 2, 3, 0, 4],
       [2, 3, 4, 0, 1],
       [0, 2, 1, 3, 4]])

In [56]:
# axis = 0 is vertical 
np.argmin(random_array , axis = 0)

array([2, 0, 0, 0, 1])

In [57]:
# axis 1 is horizontal 
np.argmax(random_array , axis = 1)

array([4, 1, 4])