In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
import numpy as np 

In [3]:
#                                         Numpy 


# creating a numpy 1d array 

arr1 = np.array([1,2,3,4,5]) ; 
print(type(arr1)) ; 



arr1

arr1.shape





<class 'numpy.ndarray'>


(5,)

In [4]:
#        creating a 2d or more dimensional numpy array 

arr = np.array([1,2,3,4,5]) ; 
# reshaping is reshape my arr into 1 row and 5 column 
arr.reshape(1,5) ;     
arr




array([1, 2, 3, 4, 5])

In [5]:
#  creating multidimensional array without using reshape 
arr2 = np.array([[1,2,3,4], [5,6,7,8]]) ; 
print(arr2) ; 
print(arr2.shape) ; 

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [6]:

# made an array and reshaped it into 5 rows and 1 column 
arr = np.arange(0,10,2).reshape(5,1) ; 
arr

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [7]:
ones = np.ones((3,4)) ; 
ones 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
#     identity matrix 

i = np.eye(3) ; 
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
#  Numpy vectorized operation 
import numpy as np 
arr1 = np.array([[1,2,3,4,5],[1,2,3,4,5]]) ; 
arr2  = np.array([[1,2,3,4,5],[1,2,3,4,5]]) ; 

print() ; 
print("Addition" , arr1+arr2) ; 
print() ; 
print("substraction" , arr1-arr2) ; 
# Element wise multiplication
print() ; 
print("Element wise multiplication " , arr1 * arr2) ; 



Addition [[ 2  4  6  8 10]
 [ 2  4  6  8 10]]

substraction [[0 0 0 0 0]
 [0 0 0 0 0]]

Element wise multiplication  [[ 1  4  9 16 25]
 [ 1  4  9 16 25]]


In [10]:
# universal function 

arr = np.array([0,30,60,90]) ; 
print(np.sqrt(arr)) ; 
print(np.log(arr)) ; 
print(np.exp(arr)) ; 
print(np.sin(arr))

[0.         5.47722558 7.74596669 9.48683298]
[      -inf 3.40119738 4.09434456 4.49980967]
[1.00000000e+00 1.06864746e+13 1.14200739e+26 1.22040329e+39]
[ 0.         -0.98803162 -0.30481062  0.89399666]


In [11]:

# Slicing 

arr = np.array([[1,2,3,4] , [5,6,7,8] , [9,10,11,12]]) ; 
#  this below line tells that go to the second row and go till the end of the row 
arr[2:]

# the below code tries to print 7,8 ,11 ,12 that is start from the first row first row and second column 
arr[1:,2:]

# start reading from zero and before the second column 
arr[0:2,2:]



array([[3, 4],
       [7, 8]])

In [12]:
# Modify the array elements 

arr[0,0] = 100
arr

arr[1:] = 200
arr 

array([[100,   2,   3,   4],
       [200, 200, 200, 200],
       [200, 200, 200, 200]])

In [13]:
#  Statistical concepts -- Normalization 
# to have a mean of  0 and standard deviation of 1 
data = np.array([1,2,3,4,5])
mean = np.mean(data) 
std_dev = np.std(data) 

#  the formulae for normalization is (Xi - mean) / standard_deviation 

normalized_data = (data - mean) / std_dev ; 
normalized_data 



array([-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356])

In [14]:
median = np.median(data)
variance = np.var(data) 




 

In [15]:
# Logical operations 

data = np.array([1,2,3,4,5,6,7,8,9,10])
data[(data > 5) & (data <= 8)]

array([6, 7, 8])