In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
import numpy as np 

# Datatypes and Attributes 

In [3]:
# Numpy main datatype is ndarray 

# 1 dimension 

a = np.array([1,2,3])

a

array([1, 2, 3])

In [4]:
# 2 dimension
a1 = np.array([[1,2,3] , [4,5,6]])
a1


array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
# 3 dimension 
a3 = np.array([[[1,2,3] , [4,5,6] , [7,8,9.3]] , [[10,11,12] , [13,14,15] , [16,17,18]]])
a3

array([[[ 1. ,  2. ,  3. ],
        [ 4. ,  5. ,  6. ],
        [ 7. ,  8. ,  9.3]],

       [[10. , 11. , 12. ],
        [13. , 14. , 15. ],
        [16. , 17. , 18. ]]])

In [6]:
a.shape , a1.shape , a3.shape

((3,), (2, 3), (2, 3, 3))

In [7]:
# dimensions of a , a1 , and a3
a.ndim , a1.ndim , a3.ndim 

(1, 2, 3)

In [8]:
# datatypes of a , a1 , and a3

a.dtype , a1.dtype , a3.dtype 

(dtype('int64'), dtype('int64'), dtype('float64'))

In [9]:
a.size , a1.size , a3.size

(3, 6, 18)

In [10]:
type(a) , type(a1) , type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

# Creating Arrays 

In [11]:
ones = np.ones(5)
ones 

one = np.ones((2,5))
one

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
print("hello")

hello
